### PR TITLE
- Updated to API 14

### PR DESCRIPTION
**Pull request by TheZoc**

### CODE REVIEW

**Comment by coding-bunny** [comment]
It works fine ingame?
No hidden function changes or anything by Carbine?

**Comment by TheZoc** [comment]
I configured it to be loaded regardless of API version, no errors since the update :)

**Comment by coding-bunny** [comment]
releasing it then :)

**Comment by TheZoc** [comment]
As a side note, I couldn't find any changes between API 13 and 14. Not sure why they changed the API version.

**Comment by coding-bunny** [comment]
best not to question the logic there :P

**Pull request merged**
